//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopRuou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietSP
    {
        public int maSP { get; set; }
        public string tenSP { get; set; }
        public Nullable<int> dungtich { get; set; }
        public Nullable<int> docol { get; set; }
        public int giaban { get; set; }
        public string xuatxu { get; set; }
        public string chitiet { get; set; }
        public string hinhanh1 { get; set; }
        public string hinhanh2 { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
