//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopRuou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhasanxuat
    {
        public int maNSX { get; set; }
        public string tenNSX { get; set; }
        public Nullable<int> maTT { get; set; }
    
        public virtual tinhtrang tinhtrang { get; set; }
    }
}
