//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopRuou.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLShopRuouEntities : DbContext
    {
        public QLShopRuouEntities()
            : base("name=QLShopRuouEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<chitietSP> chitietSPs { get; set; }
        public DbSet<loaiSP> loaiSPs { get; set; }
        public DbSet<nhasanxuat> nhasanxuats { get; set; }
        public DbSet<sanpham> sanphams { get; set; }
        public DbSet<hinhanh> hinhanhs { get; set; }
        public DbSet<tinhtrang> tinhtrangs { get; set; }
        public DbSet<loaiTK> loaiTKs { get; set; }
        public DbSet<taikhoan> taikhoans { get; set; }
    }
}
