//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopRuou.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tinhtrang
    {
        public tinhtrang()
        {
            this.loaiSPs = new HashSet<loaiSP>();
            this.nhasanxuats = new HashSet<nhasanxuat>();
        }
    
        public int maTT { get; set; }
        public string tinhtrang1 { get; set; }
    
        public virtual ICollection<loaiSP> loaiSPs { get; set; }
        public virtual ICollection<nhasanxuat> nhasanxuats { get; set; }
    }
}
